/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.WorkDefinitionRef;
import fr.n7.pDL3.WorkSequenceRef;
import fr.n7.pDL3.WorkSequenceType;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Work Sequence Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.impl.WorkSequenceRefImpl#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.WorkSequenceRefImpl#getLinkType <em>Link Type</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.WorkSequenceRefImpl#getSuccessor <em>Successor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkSequenceRefImpl extends MinimalEObjectImpl.Container implements WorkSequenceRef
{
  /**
   * The cached value of the '{@link #getPredecessor() <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredecessor()
   * @generated
   * @ordered
   */
  protected WorkDefinitionRef predecessor;

  /**
   * The default value of the '{@link #getLinkType() <em>Link Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinkType()
   * @generated
   * @ordered
   */
  protected static final WorkSequenceType LINK_TYPE_EDEFAULT = WorkSequenceType.START2START;

  /**
   * The cached value of the '{@link #getLinkType() <em>Link Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinkType()
   * @generated
   * @ordered
   */
  protected WorkSequenceType linkType = LINK_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuccessor() <em>Successor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuccessor()
   * @generated
   * @ordered
   */
  protected WorkDefinitionRef successor;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkSequenceRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL3Package.Literals.WORK_SEQUENCE_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinitionRef getPredecessor()
  {
    if (predecessor != null && predecessor.eIsProxy())
    {
      InternalEObject oldPredecessor = (InternalEObject)predecessor;
      predecessor = (WorkDefinitionRef)eResolveProxy(oldPredecessor);
      if (predecessor != oldPredecessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR, oldPredecessor, predecessor));
      }
    }
    return predecessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinitionRef basicGetPredecessor()
  {
    return predecessor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPredecessor(WorkDefinitionRef newPredecessor)
  {
    WorkDefinitionRef oldPredecessor = predecessor;
    predecessor = newPredecessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR, oldPredecessor, predecessor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkSequenceType getLinkType()
  {
    return linkType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLinkType(WorkSequenceType newLinkType)
  {
    WorkSequenceType oldLinkType = linkType;
    linkType = newLinkType == null ? LINK_TYPE_EDEFAULT : newLinkType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL3Package.WORK_SEQUENCE_REF__LINK_TYPE, oldLinkType, linkType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinitionRef getSuccessor()
  {
    if (successor != null && successor.eIsProxy())
    {
      InternalEObject oldSuccessor = (InternalEObject)successor;
      successor = (WorkDefinitionRef)eResolveProxy(oldSuccessor);
      if (successor != oldSuccessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR, oldSuccessor, successor));
      }
    }
    return successor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinitionRef basicGetSuccessor()
  {
    return successor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuccessor(WorkDefinitionRef newSuccessor)
  {
    WorkDefinitionRef oldSuccessor = successor;
    successor = newSuccessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR, oldSuccessor, successor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR:
        if (resolve) return getPredecessor();
        return basicGetPredecessor();
      case PDL3Package.WORK_SEQUENCE_REF__LINK_TYPE:
        return getLinkType();
      case PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR:
        if (resolve) return getSuccessor();
        return basicGetSuccessor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR:
        setPredecessor((WorkDefinitionRef)newValue);
        return;
      case PDL3Package.WORK_SEQUENCE_REF__LINK_TYPE:
        setLinkType((WorkSequenceType)newValue);
        return;
      case PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR:
        setSuccessor((WorkDefinitionRef)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR:
        setPredecessor((WorkDefinitionRef)null);
        return;
      case PDL3Package.WORK_SEQUENCE_REF__LINK_TYPE:
        setLinkType(LINK_TYPE_EDEFAULT);
        return;
      case PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR:
        setSuccessor((WorkDefinitionRef)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.WORK_SEQUENCE_REF__PREDECESSOR:
        return predecessor != null;
      case PDL3Package.WORK_SEQUENCE_REF__LINK_TYPE:
        return linkType != LINK_TYPE_EDEFAULT;
      case PDL3Package.WORK_SEQUENCE_REF__SUCCESSOR:
        return successor != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (linkType: ");
    result.append(linkType);
    result.append(')');
    return result.toString();
  }

} //WorkSequenceRefImpl
