/*
 * generated by Xtext 2.38.0
 */
package fr.n7.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PDL3GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cWorkdefinitionsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cColonKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cWorkDefinitionsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cWorkDefinitionsWorkDefinitionRefParserRuleCall_3_2_0 = (RuleCall)cWorkDefinitionsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cSemicolonKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cWorkDefinitionsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cWorkDefinitionsWorkDefinitionRefParserRuleCall_3_3_1_0 = (RuleCall)cWorkDefinitionsAssignment_3_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWorksequencesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cWorkSequencesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cWorkSequencesWorkSequenceRefParserRuleCall_4_2_0 = (RuleCall)cWorkSequencesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cSemicolonKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cWorkSequencesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cWorkSequencesWorkSequenceRefParserRuleCall_4_3_1_0 = (RuleCall)cWorkSequencesAssignment_4_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNotesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cGuidancesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cGuidancesGuidanceRefParserRuleCall_5_2_0 = (RuleCall)cGuidancesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cSemicolonKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cGuidancesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cGuidancesGuidanceRefParserRuleCall_5_3_1_0 = (RuleCall)cGuidancesAssignment_5_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//Process :
		//    'process' ':' name=ID
		//    ('workdefinitions' ':' workDefinitions+=WorkDefinitionRef (';' workDefinitions+=WorkDefinitionRef)* ';')?
		//    ('worksequences' ':' workSequences+=WorkSequenceRef (';' workSequences+=WorkSequenceRef)* ';')?
		//    ('notes' ':' guidances+=GuidanceRef (';' guidances+=GuidanceRef)* ';')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'process' ':' name=ID
		//('workdefinitions' ':' workDefinitions+=WorkDefinitionRef (';' workDefinitions+=WorkDefinitionRef)* ';')?
		//('worksequences' ':' workSequences+=WorkSequenceRef (';' workSequences+=WorkSequenceRef)* ';')?
		//('notes' ':' guidances+=GuidanceRef (';' guidances+=GuidanceRef)* ';')?
		public Group getGroup() { return cGroup; }
		
		//'process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//('workdefinitions' ':' workDefinitions+=WorkDefinitionRef (';' workDefinitions+=WorkDefinitionRef)* ';')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'workdefinitions'
		public Keyword getWorkdefinitionsKeyword_3_0() { return cWorkdefinitionsKeyword_3_0; }
		
		//':'
		public Keyword getColonKeyword_3_1() { return cColonKeyword_3_1; }
		
		//workDefinitions+=WorkDefinitionRef
		public Assignment getWorkDefinitionsAssignment_3_2() { return cWorkDefinitionsAssignment_3_2; }
		
		//WorkDefinitionRef
		public RuleCall getWorkDefinitionsWorkDefinitionRefParserRuleCall_3_2_0() { return cWorkDefinitionsWorkDefinitionRefParserRuleCall_3_2_0; }
		
		//(';' workDefinitions+=WorkDefinitionRef)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//';'
		public Keyword getSemicolonKeyword_3_3_0() { return cSemicolonKeyword_3_3_0; }
		
		//workDefinitions+=WorkDefinitionRef
		public Assignment getWorkDefinitionsAssignment_3_3_1() { return cWorkDefinitionsAssignment_3_3_1; }
		
		//WorkDefinitionRef
		public RuleCall getWorkDefinitionsWorkDefinitionRefParserRuleCall_3_3_1_0() { return cWorkDefinitionsWorkDefinitionRefParserRuleCall_3_3_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3_4() { return cSemicolonKeyword_3_4; }
		
		//('worksequences' ':' workSequences+=WorkSequenceRef (';' workSequences+=WorkSequenceRef)* ';')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'worksequences'
		public Keyword getWorksequencesKeyword_4_0() { return cWorksequencesKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//workSequences+=WorkSequenceRef
		public Assignment getWorkSequencesAssignment_4_2() { return cWorkSequencesAssignment_4_2; }
		
		//WorkSequenceRef
		public RuleCall getWorkSequencesWorkSequenceRefParserRuleCall_4_2_0() { return cWorkSequencesWorkSequenceRefParserRuleCall_4_2_0; }
		
		//(';' workSequences+=WorkSequenceRef)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//';'
		public Keyword getSemicolonKeyword_4_3_0() { return cSemicolonKeyword_4_3_0; }
		
		//workSequences+=WorkSequenceRef
		public Assignment getWorkSequencesAssignment_4_3_1() { return cWorkSequencesAssignment_4_3_1; }
		
		//WorkSequenceRef
		public RuleCall getWorkSequencesWorkSequenceRefParserRuleCall_4_3_1_0() { return cWorkSequencesWorkSequenceRefParserRuleCall_4_3_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_4() { return cSemicolonKeyword_4_4; }
		
		//('notes' ':' guidances+=GuidanceRef (';' guidances+=GuidanceRef)* ';')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'notes'
		public Keyword getNotesKeyword_5_0() { return cNotesKeyword_5_0; }
		
		//':'
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }
		
		//guidances+=GuidanceRef
		public Assignment getGuidancesAssignment_5_2() { return cGuidancesAssignment_5_2; }
		
		//GuidanceRef
		public RuleCall getGuidancesGuidanceRefParserRuleCall_5_2_0() { return cGuidancesGuidanceRefParserRuleCall_5_2_0; }
		
		//(';' guidances+=GuidanceRef)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//';'
		public Keyword getSemicolonKeyword_5_3_0() { return cSemicolonKeyword_5_3_0; }
		
		//guidances+=GuidanceRef
		public Assignment getGuidancesAssignment_5_3_1() { return cGuidancesAssignment_5_3_1; }
		
		//GuidanceRef
		public RuleCall getGuidancesGuidanceRefParserRuleCall_5_3_1_0() { return cGuidancesGuidanceRefParserRuleCall_5_3_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_4() { return cSemicolonKeyword_5_4; }
	}
	public class WorkDefinitionRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkDefinitionRef");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//WorkDefinitionRef :
		//    name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class WorkSequenceRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkSequenceRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPredecessorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPredecessorWorkDefinitionRefCrossReference_0_0 = (CrossReference)cPredecessorAssignment_0.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionRefIDTerminalRuleCall_0_0_1 = (RuleCall)cPredecessorWorkDefinitionRefCrossReference_0_0.eContents().get(1);
		private final Assignment cLinkTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_1_0 = (RuleCall)cLinkTypeAssignment_1.eContents().get(0);
		private final Assignment cSuccessorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSuccessorWorkDefinitionRefCrossReference_2_0 = (CrossReference)cSuccessorAssignment_2.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionRefIDTerminalRuleCall_2_0_1 = (RuleCall)cSuccessorWorkDefinitionRefCrossReference_2_0.eContents().get(1);
		
		//WorkSequenceRef :
		//    predecessor=[WorkDefinitionRef] linkType=WorkSequenceType successor=[WorkDefinitionRef]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//predecessor=[WorkDefinitionRef] linkType=WorkSequenceType successor=[WorkDefinitionRef]
		public Group getGroup() { return cGroup; }
		
		//predecessor=[WorkDefinitionRef]
		public Assignment getPredecessorAssignment_0() { return cPredecessorAssignment_0; }
		
		//[WorkDefinitionRef]
		public CrossReference getPredecessorWorkDefinitionRefCrossReference_0_0() { return cPredecessorWorkDefinitionRefCrossReference_0_0; }
		
		//ID
		public RuleCall getPredecessorWorkDefinitionRefIDTerminalRuleCall_0_0_1() { return cPredecessorWorkDefinitionRefIDTerminalRuleCall_0_0_1; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_1() { return cLinkTypeAssignment_1; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_1_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_1_0; }
		
		//successor=[WorkDefinitionRef]
		public Assignment getSuccessorAssignment_2() { return cSuccessorAssignment_2; }
		
		//[WorkDefinitionRef]
		public CrossReference getSuccessorWorkDefinitionRefCrossReference_2_0() { return cSuccessorWorkDefinitionRefCrossReference_2_0; }
		
		//ID
		public RuleCall getSuccessorWorkDefinitionRefIDTerminalRuleCall_2_0_1() { return cSuccessorWorkDefinitionRefIDTerminalRuleCall_2_0_1; }
	}
	public class GuidanceRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.GuidanceRef");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_0 = (RuleCall)cTextAssignment.eContents().get(0);
		
		//GuidanceRef :
		//    text=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//text=STRING
		public Assignment getTextAssignment() { return cTextAssignment; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_0() { return cTextSTRINGTerminalRuleCall_0; }
	}
	
	public class WorkSequenceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.PDL3.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStart2startEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStart2startS2sKeyword_0_0 = (Keyword)cStart2startEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinish2startEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinish2startF2sKeyword_1_0 = (Keyword)cFinish2startEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStart2finishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStart2finishS2fKeyword_2_0 = (Keyword)cStart2finishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinish2finishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinish2finishF2fKeyword_3_0 = (Keyword)cFinish2finishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType :
		//    start2start='s2s'
		//    | finish2start='f2s'
		//    | start2finish='s2f'
		//    | finish2finish='f2f'
		//;
		public EnumRule getRule() { return rule; }
		
		//start2start='s2s'
		//| finish2start='f2s'
		//| start2finish='s2f'
		//| finish2finish='f2f'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//start2start='s2s'
		public EnumLiteralDeclaration getStart2startEnumLiteralDeclaration_0() { return cStart2startEnumLiteralDeclaration_0; }
		
		//'s2s'
		public Keyword getStart2startS2sKeyword_0_0() { return cStart2startS2sKeyword_0_0; }
		
		//finish2start='f2s'
		public EnumLiteralDeclaration getFinish2startEnumLiteralDeclaration_1() { return cFinish2startEnumLiteralDeclaration_1; }
		
		//'f2s'
		public Keyword getFinish2startF2sKeyword_1_0() { return cFinish2startF2sKeyword_1_0; }
		
		//start2finish='s2f'
		public EnumLiteralDeclaration getStart2finishEnumLiteralDeclaration_2() { return cStart2finishEnumLiteralDeclaration_2; }
		
		//'s2f'
		public Keyword getStart2finishS2fKeyword_2_0() { return cStart2finishS2fKeyword_2_0; }
		
		//finish2finish='f2f'
		public EnumLiteralDeclaration getFinish2finishEnumLiteralDeclaration_3() { return cFinish2finishEnumLiteralDeclaration_3; }
		
		//'f2f'
		public Keyword getFinish2finishF2fKeyword_3_0() { return cFinish2finishF2fKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final WorkDefinitionRefElements pWorkDefinitionRef;
	private final WorkSequenceRefElements pWorkSequenceRef;
	private final GuidanceRefElements pGuidanceRef;
	private final WorkSequenceTypeElements eWorkSequenceType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDL3GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pWorkDefinitionRef = new WorkDefinitionRefElements();
		this.pWorkSequenceRef = new WorkSequenceRefElements();
		this.pGuidanceRef = new GuidanceRefElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.PDL3".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process :
	//    'process' ':' name=ID
	//    ('workdefinitions' ':' workDefinitions+=WorkDefinitionRef (';' workDefinitions+=WorkDefinitionRef)* ';')?
	//    ('worksequences' ':' workSequences+=WorkSequenceRef (';' workSequences+=WorkSequenceRef)* ';')?
	//    ('notes' ':' guidances+=GuidanceRef (';' guidances+=GuidanceRef)* ';')?
	//;
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//WorkDefinitionRef :
	//    name=ID
	//;
	public WorkDefinitionRefElements getWorkDefinitionRefAccess() {
		return pWorkDefinitionRef;
	}
	
	public ParserRule getWorkDefinitionRefRule() {
		return getWorkDefinitionRefAccess().getRule();
	}
	
	//WorkSequenceRef :
	//    predecessor=[WorkDefinitionRef] linkType=WorkSequenceType successor=[WorkDefinitionRef]
	//;
	public WorkSequenceRefElements getWorkSequenceRefAccess() {
		return pWorkSequenceRef;
	}
	
	public ParserRule getWorkSequenceRefRule() {
		return getWorkSequenceRefAccess().getRule();
	}
	
	//GuidanceRef :
	//    text=STRING
	//;
	public GuidanceRefElements getGuidanceRefAccess() {
		return pGuidanceRef;
	}
	
	public ParserRule getGuidanceRefRule() {
		return getGuidanceRefAccess().getRule();
	}
	
	//enum WorkSequenceType :
	//    start2start='s2s'
	//    | finish2start='f2s'
	//    | start2finish='s2f'
	//    | finish2finish='f2f'
	//;
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
