/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Guidance Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.GuidanceRef#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL3.PDL3Package#getGuidanceRef()
 * @model
 * @generated
 */
public interface GuidanceRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see fr.n7.pDL3.PDL3Package#getGuidanceRef_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.GuidanceRef#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // GuidanceRef
