/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.pDL3.PDL3Factory
 * @model kind="package"
 * @generated
 */
public interface PDL3Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pDL3";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/PDL3";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pDL3";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PDL3Package eINSTANCE = fr.n7.pDL3.impl.PDL3PackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.pDL3.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.pDL3.impl.ProcessImpl
   * @see fr.n7.pDL3.impl.PDL3PackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Work Definitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__WORK_DEFINITIONS = 1;

  /**
   * The feature id for the '<em><b>Work Sequences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__WORK_SEQUENCES = 2;

  /**
   * The feature id for the '<em><b>Guidances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__GUIDANCES = 3;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.pDL3.impl.WorkDefinitionRefImpl <em>Work Definition Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.pDL3.impl.WorkDefinitionRefImpl
   * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkDefinitionRef()
   * @generated
   */
  int WORK_DEFINITION_REF = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>Work Definition Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.pDL3.impl.WorkSequenceRefImpl <em>Work Sequence Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.pDL3.impl.WorkSequenceRefImpl
   * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkSequenceRef()
   * @generated
   */
  int WORK_SEQUENCE_REF = 2;

  /**
   * The feature id for the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_REF__PREDECESSOR = 0;

  /**
   * The feature id for the '<em><b>Link Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_REF__LINK_TYPE = 1;

  /**
   * The feature id for the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_REF__SUCCESSOR = 2;

  /**
   * The number of structural features of the '<em>Work Sequence Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_REF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.pDL3.impl.GuidanceRefImpl <em>Guidance Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.pDL3.impl.GuidanceRefImpl
   * @see fr.n7.pDL3.impl.PDL3PackageImpl#getGuidanceRef()
   * @generated
   */
  int GUIDANCE_REF = 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUIDANCE_REF__TEXT = 0;

  /**
   * The number of structural features of the '<em>Guidance Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUIDANCE_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.pDL3.WorkSequenceType <em>Work Sequence Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.pDL3.WorkSequenceType
   * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkSequenceType()
   * @generated
   */
  int WORK_SEQUENCE_TYPE = 4;


  /**
   * Returns the meta object for class '{@link fr.n7.pDL3.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see fr.n7.pDL3.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.pDL3.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.pDL3.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.pDL3.Process#getWorkDefinitions <em>Work Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Work Definitions</em>'.
   * @see fr.n7.pDL3.Process#getWorkDefinitions()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_WorkDefinitions();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.pDL3.Process#getWorkSequences <em>Work Sequences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Work Sequences</em>'.
   * @see fr.n7.pDL3.Process#getWorkSequences()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_WorkSequences();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.pDL3.Process#getGuidances <em>Guidances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Guidances</em>'.
   * @see fr.n7.pDL3.Process#getGuidances()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Guidances();

  /**
   * Returns the meta object for class '{@link fr.n7.pDL3.WorkDefinitionRef <em>Work Definition Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Definition Ref</em>'.
   * @see fr.n7.pDL3.WorkDefinitionRef
   * @generated
   */
  EClass getWorkDefinitionRef();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.pDL3.WorkDefinitionRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.pDL3.WorkDefinitionRef#getName()
   * @see #getWorkDefinitionRef()
   * @generated
   */
  EAttribute getWorkDefinitionRef_Name();

  /**
   * Returns the meta object for class '{@link fr.n7.pDL3.WorkSequenceRef <em>Work Sequence Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Sequence Ref</em>'.
   * @see fr.n7.pDL3.WorkSequenceRef
   * @generated
   */
  EClass getWorkSequenceRef();

  /**
   * Returns the meta object for the reference '{@link fr.n7.pDL3.WorkSequenceRef#getPredecessor <em>Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Predecessor</em>'.
   * @see fr.n7.pDL3.WorkSequenceRef#getPredecessor()
   * @see #getWorkSequenceRef()
   * @generated
   */
  EReference getWorkSequenceRef_Predecessor();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.pDL3.WorkSequenceRef#getLinkType <em>Link Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Type</em>'.
   * @see fr.n7.pDL3.WorkSequenceRef#getLinkType()
   * @see #getWorkSequenceRef()
   * @generated
   */
  EAttribute getWorkSequenceRef_LinkType();

  /**
   * Returns the meta object for the reference '{@link fr.n7.pDL3.WorkSequenceRef#getSuccessor <em>Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Successor</em>'.
   * @see fr.n7.pDL3.WorkSequenceRef#getSuccessor()
   * @see #getWorkSequenceRef()
   * @generated
   */
  EReference getWorkSequenceRef_Successor();

  /**
   * Returns the meta object for class '{@link fr.n7.pDL3.GuidanceRef <em>Guidance Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guidance Ref</em>'.
   * @see fr.n7.pDL3.GuidanceRef
   * @generated
   */
  EClass getGuidanceRef();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.pDL3.GuidanceRef#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see fr.n7.pDL3.GuidanceRef#getText()
   * @see #getGuidanceRef()
   * @generated
   */
  EAttribute getGuidanceRef_Text();

  /**
   * Returns the meta object for enum '{@link fr.n7.pDL3.WorkSequenceType <em>Work Sequence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Work Sequence Type</em>'.
   * @see fr.n7.pDL3.WorkSequenceType
   * @generated
   */
  EEnum getWorkSequenceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PDL3Factory getPDL3Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.pDL3.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.pDL3.impl.ProcessImpl
     * @see fr.n7.pDL3.impl.PDL3PackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Work Definitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__WORK_DEFINITIONS = eINSTANCE.getProcess_WorkDefinitions();

    /**
     * The meta object literal for the '<em><b>Work Sequences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__WORK_SEQUENCES = eINSTANCE.getProcess_WorkSequences();

    /**
     * The meta object literal for the '<em><b>Guidances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__GUIDANCES = eINSTANCE.getProcess_Guidances();

    /**
     * The meta object literal for the '{@link fr.n7.pDL3.impl.WorkDefinitionRefImpl <em>Work Definition Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.pDL3.impl.WorkDefinitionRefImpl
     * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkDefinitionRef()
     * @generated
     */
    EClass WORK_DEFINITION_REF = eINSTANCE.getWorkDefinitionRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION_REF__NAME = eINSTANCE.getWorkDefinitionRef_Name();

    /**
     * The meta object literal for the '{@link fr.n7.pDL3.impl.WorkSequenceRefImpl <em>Work Sequence Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.pDL3.impl.WorkSequenceRefImpl
     * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkSequenceRef()
     * @generated
     */
    EClass WORK_SEQUENCE_REF = eINSTANCE.getWorkSequenceRef();

    /**
     * The meta object literal for the '<em><b>Predecessor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE_REF__PREDECESSOR = eINSTANCE.getWorkSequenceRef_Predecessor();

    /**
     * The meta object literal for the '<em><b>Link Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE_REF__LINK_TYPE = eINSTANCE.getWorkSequenceRef_LinkType();

    /**
     * The meta object literal for the '<em><b>Successor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE_REF__SUCCESSOR = eINSTANCE.getWorkSequenceRef_Successor();

    /**
     * The meta object literal for the '{@link fr.n7.pDL3.impl.GuidanceRefImpl <em>Guidance Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.pDL3.impl.GuidanceRefImpl
     * @see fr.n7.pDL3.impl.PDL3PackageImpl#getGuidanceRef()
     * @generated
     */
    EClass GUIDANCE_REF = eINSTANCE.getGuidanceRef();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUIDANCE_REF__TEXT = eINSTANCE.getGuidanceRef_Text();

    /**
     * The meta object literal for the '{@link fr.n7.pDL3.WorkSequenceType <em>Work Sequence Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.pDL3.WorkSequenceType
     * @see fr.n7.pDL3.impl.PDL3PackageImpl#getWorkSequenceType()
     * @generated
     */
    EEnum WORK_SEQUENCE_TYPE = eINSTANCE.getWorkSequenceType();

  }

} //PDL3Package
